[build]
  command = "npm run build"
  publish = "out"

# Since we're using static export, we don't need the Next.js plugin
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

# Make sure all routes are handled correctly with SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# No need for special redirects for static assets in static export
# as they're already in the correct location

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false 