[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# Make sure all routes are handled correctly with SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle static assets from public directory
[[redirects]]
  from = "/videos/*"
  to = "/.next/public/videos/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/.next/public/images/:splat"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false 